### ISSUE TITLE
Request for dataset used in your paper

### ISSUE THREAD

**Issue by Burton123456** [DeMoriarty/fast_pytorch_kmeans#23]
I would like to request access to the BBS dataset used in your study for further research purposes，which consists of three data sets. Each dataset includes 270 template-image pairs and each image pair consist of frames f and f + ∆f，where f was randomly chosen and ∆f ∈ {25, 50, 100}.
If you could provide me with specific information and download links for the dataset, I would greatly appreciate it. Thank you for your time and assistance!

**Comment by DeMoriarty** [comment]
If you're referring to [this paper](https://arxiv.org/pdf/2306.15010.pdf), I'm not the author of it. [this]( https://github.com/aktgpt/vq-nnf) is probably what you're looking for.
