### ISSUE TITLE
Need Requirement .txt file to run it on anaconda

### ISSUE THREAD

**Issue by hammad2008** [DeMoriarty/fast_pytorch_kmeans#8]
Hello I hope you are doing well. I  Need Requirement .txt file to run it on anaconda can you please upload that

**Comment by hammad2008** [comment]
@DeMoriarty  @TheProjectsGuy Can you please help me with that?

**Comment by DeMoriarty** [comment]
fast_pytorch_kmeans is only available via pip, you can run `pip install fast-pytorch-kmeans` in your anaconda environment to install. 
There are only 3 required packages: torch, numpy and pynvml, all can be found in setup.py. if necessary, you may clone this repository and simply create requirements.txt listing these 3 packages, and build the package manually. But usually setup.py should be sufficient to install this package as well as its dependecies via pip.
